import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "@/store/ReactQueryProvider";
import { Toaster } from "sonner";
import { Footer, Header } from "@/components/shared";
import { DM_Sans } from "next/font/google";
import { cn } from "@/lib/utils";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Karla:ital,wght@0,200..800;1,200..800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={cn(
          dmSans.className,
          "antialiased bg-bg h-screen overflow-x-hidden relative"
        )}
      >
        <ReactQueryProvider>
          <Toaster position="top-right" richColors />
          <main className="w-full min-h-screen">
            <Header />
            {children}
            <Footer />
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
