import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "@/store/ReactQueryProvider";
import { Toaster } from "sonner";
import { Header } from "@/components/shared";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <Toaster position="top-right" richColors />
          <main className="bg-black-bg w-full min-h-screen">
            <Header />
            {children}
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
