export const techCompetitionsData = [
  {
    category: "Tech",
    name: "Web Development",
    shortDescription: "Build a web application from scratch.",
    description:
      "Participants will build a fully functional web application using modern web technologies.",
    minMembers: 1,
    maxMembers: 3,
    rulebookUrl: "https://example.com/web-dev",
    href: "/competitions/web-development",
    color: "fuchsia",
    image: "/assets/images/pill.png",
  },
  {
    category: "Tech",
    name: "App Development",
    shortDescription: "Develop a mobile application.",
    description:
      "Participants will create a mobile app for either Android or iOS platforms.",
    minMembers: 1,
    maxMembers: 4,
    rulebookUrl: "https://example.com/app-dev",
    href: "/competitions/app-development",
    color: "lime",
    image: "/assets/images/hemisphere.png",
  },
  {
    category: "Tech",
    name: "Machine Learning",
    shortDescription: "Create visual representations of data.",
    description:
      "Participants will use Machine Learning to create insightful visual representations of complex data sets.",
    minMembers: 1,
    maxMembers: 3,
    rulebookUrl: "https://example.com/data-visualization",
    href: "/competitions/data-visualization",
    color: "cyan",
    image: "/assets/images/torus.png",
  },
  {
    category: "Tech",
    name: "SQL Query",
    shortDescription: "Write efficient SQL queries.",
    description:
      "Participants will solve problems by writing efficient SQL queries to retrieve and manipulate data.",
    minMembers: 1,
    maxMembers: 2,
    rulebookUrl: "https://example.com/sql-query",
    href: "/competitions/sql-query",
    color: "violet",
    image: "/assets/images/torus-knot.png",
  },
  {
    category: "Tech",
    name: "Pseudocode",
    shortDescription: "Write pseudocode for given problems.",
    description:
      "Participants will write pseudocode to solve algorithmic problems, focusing on logic and structure.",
    minMembers: 1,
    maxMembers: 2,
    rulebookUrl: "https://example.com/pseudocode",
    href: "/competitions/pseudocode",
    color: "cyan",
    image: "/assets/images/cube.png",
  },
  {
    category: "Tech",
    name: "UI/UX",
    shortDescription: "Design user interfaces and experiences.",
    description:
      "Participants will design user interfaces and experiences that are both functional and aesthetically pleasing.",
    minMembers: 1,
    maxMembers: 3,
    rulebookUrl: "https://example.com/ui-ux",
    href: "/competitions/ui-ux",
    color: "lime",
    image: "/assets/images/cone.png",
  },
  {
    category: "Tech",
    name: "Speed Debugging",
    shortDescription: "Debug code as quickly as possible.",
    description:
      "Participants will be given buggy code and must find and fix the errors as quickly as possible.",
    minMembers: 1,
    maxMembers: 2,
    rulebookUrl: "https://example.com/speed-debugging",
    href: "/competitions/speed-debugging",
    color: "violet",
    image: "/assets/images/cylinder.png",
  },
];

export const nonTechCompetitionsData = [
  {
    category: "Non-Tech",
    name: "Quiz Competition",
    shortDescription: "Test your knowledge across various topics.",
    description:
      "Participants will compete in a quiz covering a wide range of topics. The team with the highest score wins.",
    minMembers: 1,
    maxMembers: 4,
    rulebookUrl: "https://example.com/quiz",
    href: "/competitions/quiz",
    color: "blue",
    image: "/assets/images/cylinder-blue.png",
  },
  {
    category: "Non-Tech",
    name: "Essay Writing Competition",
    shortDescription: "Showcase your writing skills.",
    description:
      "Participants will write essays on given topics. The best essays will be judged based on creativity, coherence, and grammar.",
    minMembers: 1,
    maxMembers: 1,
    rulebookUrl: "https://example.com/essay-writing",
    href: "/competitions/essay-writing",
    color: "fuchsia",
    image: "/assets/images/cog.png",
  },
  {
    category: "Non-Tech",
    name: "CS 1.6 Gaming Competition",
    shortDescription: "Compete in the classic Counter-Strike 1.6.",
    description:
      "Teams will compete in Counter-Strike 1.6 matches. The team that wins the most rounds will be declared the winner.",
    minMembers: 5,
    maxMembers: 5,
    rulebookUrl: "https://example.com/cs-1-6",
    href: "/competitions/cs-1-6",
    color: "lime",
    image: "/assets/images/torus-blue.png",
  },
  {
    category: "Non-Tech",
    name: "FIFA Competition",
    shortDescription: "Show your skills in FIFA.",
    description:
      "Participants will compete in FIFA matches. The player with the highest score will win the competition.",
    minMembers: 1,
    maxMembers: 1,
    rulebookUrl: "https://example.com/fifa",
    href: "/competitions/fifa",
    color: "cyan",
    image: "/assets/images/half-torus.png",
  },
  {
    category: "Non-Tech",
    name: "TEKKEN Competition",
    shortDescription: "Fight your way to the top in TEKKEN.",
    description:
      "Participants will compete in TEKKEN matches. The player who wins the most rounds will be declared the champion.",
    minMembers: 1,
    maxMembers: 1,
    rulebookUrl: "https://example.com/tekken",
    href: "/competitions/tekken",
    color: "violet",
    image: "/assets/images/cube-helix 1.png",
  },
];

export const comeptitionNames = [
  // Tech Competitions
  { name: "Web Development", maxMembers: 2 },
  { name: "App Development", maxMembers: 2 },
  { name: "Machine Learning", maxMembers: 3 },
  { name: "SQL Query", maxMembers: 2 },
  { name: "Pseudocode", maxMembers: 2 },
  { name: "UI/UX", maxMembers: 3 },
  { name: "Speed Debugging", maxMembers: 2 },
  // Non-Tech Competitions
  { name: "Quiz Competition", maxMembers: 2 },
  { name: "Essay Writing Competition", maxMembers: 1 },
  { name: "CS 1.6 Gaming Competition", maxMembers: 2 },
  { name: "FIFA Competition", maxMembers: 1 },
  { name: "TEKKEN Competition", maxMembers: 1 },
];
